# 服务器配置
server:
  port: ":8082"

# 数据库配置
database:
  driver: "mysql"
  dsn: "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 100
  max_idle_conns: 20
  conn_max_lifetime: 3600  # 连接最大存活时间(秒)

# JWT配置
jwt:
  secret: "myjwt@secretkey_"
  expire_hours: 24  # 过期时间(小时)

# 日志配置
log:
  level: "debug" # panic fatal error warn/warning info debug trace
  max_age: 7  # 日志保存时间 （天）
  output_path: "./logs/logs-"
